ALTER TABLE LOTACAO ADD FOREIGN KEY (cargoID) REFERENCES CARGO (id);
ALTER TABLE LOTACAO ADD FOREIGN KEY (departamentoID) REFERENCES DEPARTAMENTO (id);
ALTER TABLE LOTACAO ADD FOREIGN KEY (funcionarioID) REFERENCES FUNCIONARIO (id);